### ISSUE TITLE
Exercise 5 console.log not returning anything.

### ISSUE THREAD

**Issue by crispinha** [evanlucas/learnyoumongo#34] opened 2016-03-16 23:15 UTC
All console.log calls in exercise 5 using `learnyoumongo run [filename]` don't return anything. This might be by design, but I can't debug anything using this.
I'm on OSX 10.11, using Node v5.6.0, Mongo v3.0.7 and Learnyoumongo v3.0.1
EDIT It's not a platform-specific thing, it also fails on Ubuntu 14.04.4 with Node v4.4.0, Mongo v2.4.9, and learnyoumongo v3.0.1

My code: 

``` javascript
console.log(process.argv);
MongoClient = require('mongodb').MongoClient;
console.log(MongoClient);
```

Output:

``` bash
Crispin-laptop:mongo crispin$ learnyoumongo run insert.js
Crispin-laptop:mongo crispin$
```

**Comment by unValerio** [comment] 2016-03-20 08:49
Same issue:
OSX 10.11.1, Node v0.12.7, Mongo v3.2.4, Learnyoumongo v3.0.1

**Comment by crispinha** [comment] 2016-03-22 00:24
Exercise 6 works, which makes me think that this is a bug, but E5 does use console.log for checking answers, so this might be by design. I'll have a look in the code and report back.
Part 2:
[This line](https://github.com/evanlucas/learnyoumongo/blob/7a739268f8dabe56e484b16d1e632344c7aff8b5/exercises/insert/exercise.js#L116) might be what's doing it, I'll check on an offline copy.
EDIT: Not by itself. I don't understand Workshopper to do anything more than guess at what does what, so I don't think I can do any more here.
Part 3:
I'm trying out some alternatives to console log: 
- console.warn() - no luck
- console.error() - nope
- console.dir() - nothing

Part 4:
It's not a platform-specific thing, it fails on Ubuntu 14.04.4 with Node v4.4.0, Mongo v2.4.9, and learnyoumongo v3.0.1

Part 5 (24/3/2016 NZDT):
I've tried commenting out all instances of "stdout" in insert/exercise.js. No luck. [A quick check of the diff between this exercise and the one before](https://www.diffchecker.com/xxjksgj2) shows nothing that would be blocking console.log.

**Comment by dvlpstrcrispin** [comment] 2016-03-22 00:32
[This line](https://github.com/evanlucas/learnyoumongo/blob/7a739268f8dabe56e484b16d1e632344c7aff8b5/exercises/insert/exercise.js#L111) might be what's doing it, I'll check on an offline copy.

**Comment by dvlpstrcrispin** [comment] 2016-03-22 01:10
I'm trying out some alternatives to console log: 

- console.warn() - no luck
- console.error() - nope
- console.dir() - nothing

**Comment by dvlpstrcrispin** [comment] 2016-03-22 01:29
It's not a platform-specific thing, it fails on Ubuntu 14.04.4 with Node v4.4.0, Mongo v2.4.9, and learnyoumongo v3.0.1

**Comment by domparry** [comment] 2016-05-16 04:47
Same issue here on OSX 10.11.1

**Comment by domparry** [comment] 2016-05-16 14:31
I seem to have found something. The line:

exercise = comparestdout(exercise)

is missing from Exercise 5. It's just after the line:

exercise = execute(exercise)

in exercise 4. Once I add it, I get messages to the console....

**Comment by domparry** [comment] 2016-05-16 15:39
Update: So the above does allow me to see my console.log outputs, but it breaks the verify processor. Seems this exercise implements it's own processor as follows, which breaks Stdout somehow. I still can't figure out where yet:

exercise.addProcessor(function(mode, cb) {
  var orig
  this.submissionStdout.pipe(sub)
  var args = this.solutionArgs
  sub.on('data', function(chunk) {
    chunk = chunk.toString()
    if (chunk)
      try {
        orig = JSON.parse(chunk)
        delete orig._id
      }
      catch (err) {
        exercise.emit('fail', 'Unable to parse JSON. ' +
          'Did you stringify the output?')
        cb(err)
      }
  })

  if (mode === 'verify') {
    sub.on('end', function() {
      if (orig) {
        findDoc(args, function(err, doc) {
          if (err) return cb(err)
          orig = sortObj(orig)
          doc = sortObj(doc)
          try {
            compare(orig, doc)
            cb(null, true)
          }
          catch (e) {
            console.log(e)
            exercise.emit('fail', e.message)
            cb(null, false)
          }
          //sub.end()
        })
      } else {
        cb(null, false)
      }
    })
  }
  this.submissionStdout = through2()
  if (mode === 'verify')
    this.solutionStdout = through2()

  if (mode === 'run') {
    sub.pipe(process.stdout)
    process.nextTick(function() {
      cb(null, true)
    })
  }
})

**Comment by manters2000** [comment] 2016-05-18 23:20
Having the same issue here, can't also get to work this problem here in my end.

**Comment by evanlucas** [comment] 2016-05-19 11:52
Yes, this exercise purposefully compares stdout of both your script and one executing the expected way. Closing as this is by design. (If you have a better way of doing this, I am all ears :])

**Closed as completed by evanlucas** 2016-05-19 11:52 UTC
